---
- hosts: linux
  user: sysadmin
  become: true

  tasks:

  - name: Update de paquetes Rocky
    ansible.builtin.yum:
      name: "*"
      state: latest
    when: ansible_os_family == "RedHat"
    notify: Reinicio del server
    
  - name: Update de paquetes Ubuntu
    ansible.builtin.apt:
      name: "*"
      state: latest
      update_cache: yes
    when: ansible_os_family == "Debian"
    notify: Reinicio del server