---
- hosts: linux
  user: sysadmin
  become: true

  tasks:

  - name: Copia de llave publica desde archivo local
    ansible.posix.authorized_key:
      user: sysadmin
      state: present # Si la clave esta no la copia
      key: "{{ lookup('file', '/home/sysadmin/.ssh/id_rsa.pub') }}"


  - name: No permitir ssh con root
    ansible.builtin.lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^(P|#P)ermitRootLogin'
      line: "PermitRootLogin no"
    notify: Reinicio de servicio ssh


  - name: No permitir ssh con user y pass
    ansible.builtin.lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^asswordAuthentication='
      line: "PasswordAuthentication no"
    notify: Reinicio de servicio ssh

  handlers:

  - name: Reinicio del server
    ansible.builtin.reboot:
      reboot_timeout: 300
  
  - name: Reinicio de servicio ssh
    ansible.builtin.systemd:
      name: sshd
      state: restarted